---
title: Select, Download, and Save a State EEIO Model locally"
output:
  md_document:
    variant: gfm
params:
  year:
    label: "Model Year"
    value: 2012
    input: select
    multiple: FALSE
    choices: [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
  state:
    label: "State"
    value: ""
    input: select
    choices: ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL",
              "IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT",
              "NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI",
              "SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"]
  write:
    label: "Write to Excel?"
    value: FALSE
---

```{r setup, include=FALSE}
source("R/utils.R")

# Stop execution of Rmd if params not selected
if (params$state=="") {
  stop("You must select a state and a year.")
}

## Select model build parameters
state <- params$state
year <- params$year

modelstub <- 'EEIOv1.0-s-'
modelname <- paste0(state, modelstub,substr(year,3,4)) 

```

```{r load-model, echo=FALSE}

file_name <- paste0(modelname,".rds")

file_url <- paste0("https://dmap-data-commons-ord.s3.amazonaws.com/USEEIO-State/",file_name)

directory <- "models/"

file_path <- paste0(directory,file_name)

if(!file.exists(file_path)) {
  if (!dir.exists(directory)) {
    dir.create(directory, recursive = TRUE)
  }
  # Download file
  utils::download.file(file_url,file_path,
                       mode = "wb", quiet = TRUE)
  print(paste0("Downloading model for ", state, " in ", year, " to ", file_path, "."))
} else {
  print(paste("File already exists at", file_path))
}

model <- readRDS(file_path) # Test that it loads correctly

```


```{r write_model, eval=params$write, echo=FALSE}
install_useeior()
# write model to Excel
output_dir <- file.path('output')
dir.create(output_dir, showWarnings = FALSE)

useeior::writeModeltoXLSX(model, output_dir)

print(paste0("Model for ", state, " in ", year, " written to Excel at ", output_dir, "."))
```

