---
title: Write a local State EEIO Model to Excel"
output:
  md_document:
    variant: gfm
params:
  year:
    label: "Model Year"
    value: 2012
    input: select
    multiple: FALSE
    choices: [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
  state:
    label: "State"
    value: ""
    input: select
    choices: ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL",
              "IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT",
              "NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI",
              "SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"]
---

```{r setup, include=FALSE}
library(useeior)
source("R/utils.R")

# Stop execution of Rmd if params not selected
if (params$state=="") {
  stop("You must select a state and a year.")
}

## Select model build parameters
state <- params$state
year <- params$year

modelstub <- 'EEIOv1.0-s-'
modelname <- paste0(state, modelstub,substr(year,3,4)) 

```

```{r load-model, include=FALSE}

file_name <- paste0(modelname, ".rds")
directory <- "models/"
file_path <- paste0(directory, file_name)

if (file.exists(file_path)) {
  model <- readRDS(file_path)
} else {
  stop("Model not found locally, first run DownloadandSaveModelLocally.Rmd")
}

# write model to Excel
output_dir <- file.path('output')
dir.create(output_dir, showWarnings = FALSE)

writeModeltoXLSX(model, output_dir)

```

Model for `r state` in `r year` written to Excel at `r output_dir`.
