---
title: Consumption-Based Emissions Results Using a State EEIO Model
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  officedown::rdocx_document:
    fig_caption: true

params:
  model:
    label: "Model Type"
    value: "v1.1-GHG"
    input: select
    choices: ["v1.1-GHG","v1.1-GHGc"]
  years:
    label: "Model Year"
    value: [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
    input: select
    multiple: TRUE
    choices: [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
  state:
    label: "State"
    value: ""
    input: select
    multiple: FALSE
    choices: ["CT","NH","ME","MA","NY","NJ","RI","VT"] #"AK","AZ","AR","CA","CO",,"DE","FL","GA","HI","ID","IL",
#"IN","IA","KS","KY","LA",,"MD","MI","MN","MS","MO","MT",
#"NE","NV","NM","NC","ND","OH","OK","OR","PA",
#"SC","SD","TN","TX","UT","VA","WA","WV","WI","WY"]
---

```{r setup, include=FALSE}
source("../R/utils.R")
install_useeior()
source("../R/StateEEIOFigures.R")
source("../R/StateEEIOCalculations.R")
library(useeior)
# devtools::load_all("../../useeior/") # Requires develop branch (to be v1.6.0)

# Stop execution of Rmd if params not selected
if (params$state=="") {
  stop("You must select a state and a year.")
}

## Select model build parameters
state <- params$state
years <- params$years
spec <- params$model

focal_year <- max(years)

indicator <- "Greenhouse Gases"

if (spec == "v1.1-GHG") {
  modelstub <- 'EEIOv1.1-GHG-'
} else if (spec == "v1.1-GHGc") {
  modelstub <- 'EEIOv1.1-GHGc-'  
}

```

```{r load-models, echo=FALSE}

models <- list()
for(y in years) {
   modelname <- paste0(state, modelstub, substr(y,3,4))
   name_for_list <- paste0(state,"-",toString(y))
   file_path <- file.path("..","models",paste0(modelname,".rds"))
   models[[name_for_list]] <- readRDS(file_path)
}


```

*Table of Figures*
```{r echo=FALSE}
library(officedown)
library(officer)
block_toc(seq_id = "fig") # or "tab" for tables
# block_toc(style = "Image Caption") # or "Table Caption" for tables
```

Add introductory text here.

```{r calculate_results, include=FALSE}

cbe_all <- sapply(models,calculateStateCBE,simplify=TRUE,USE.NAMES=TRUE)
row.names(cbe_all) <- row.names(calculateStateCBE(models[[1]]))

cbe_agg_soi <- aggregateStateResultMatrix(models[[1]], cbe_all, region=state)
cbe_agg_rous <- aggregateStateResultMatrix(models[[1]], cbe_all, region='RoUS')
cbe_agg_row <- aggregateStateResultMatrix(models[[1]], cbe_all, region='RoW')

households_all <- sapply(models, calculateHouseholdShares, indicator=indicator, simplify=TRUE, USE.NAMES=TRUE)
rownames(households_all) <- rownames(calculateHouseholdShares(models[[1]], indicator))


```
```{r cbe_results, echo=FALSE, results='asis', fig.height=4, fig.width=6.5, warning=FALSE}
cbe_by_year_list <- c()
for(y in years) {
  col <- paste0(state, "-", y)
  cbe_agg_soi_year <- as.matrix(cbe_agg_soi[, col])
  cbe_agg_rous_year <- as.matrix(cbe_agg_rous[, col])
  cbe_agg_row_year <- as.matrix(cbe_agg_row[, col])

  v <- c(RoUS='cbe_agg_rous_year', RoW='cbe_agg_row_year')
  v[state] <- 'cbe_agg_soi_year' # Set state specific name for this vector
  ghgs <- combineResults(v)
  ghgs$Value <- ghgs$Value / 10^9
  ghgs <- subset(ghgs, !(ghgs$Sector %in% c("Used", "Other")))
  
  # Split Household Shares before developing figure
  households <- as.data.frame(households_all[, col, drop=FALSE])
  households <- cbind(newSector= rownames(households), households)
  households$Sector <- "F010"
  ghgs2 <- merge(ghgs, households, by = "Sector", all.x=TRUE)
  idx <- !is.na(ghgs2$newSector)
  ghgs2$Sector[idx] <- ghgs2$newSector[idx]
  ghgs2$Value[idx] <- ghgs2$Value[idx] * ghgs2[idx, col]
  ghgs <- ghgs2[c("ID", "Sector", "Value")]
  
  p <- stackedBarChartResultFigure(ghgs, models[[col]])
  p <- p + 
    xlab('Greenhouse Gases (million tonnes)') +
    labs(fill = 'Region') +
    ggtitle(col) +
    theme(axis.text.y = element_text(size = 7))
  cbe_by_year_list[[toString(y)]] <- p
}

```

Text goes here to describe the demand. (Figure \@ref(fig:demand-1) and also Figure \@ref(fig:demand-2)).

```{r time_series_demand, echo=FALSE, fig.width=6.5, fig.height=4}

demand_types <- c(state, "RoUS", "RoW", "Total")
ylabel <- paste0("Billion $ (",focal_year,")")
d <- sapply(models, calculateDemandByRegion, price_year=focal_year)
rownames(d) <- demand_types
p <- lineChartFigure(d / 10^9,ylabel)
p <- p + theme(text = element_text(size=12))
p
fig_num <- run_autonum(seq_id = "fig", pre_label = "Figure ", bkm = "demand-1")
block_caption("Demand by region",
              style = "Image Caption",
              autonum = fig_num
              )

demand_types <- c("Household", "Investment", "Federal Government", "State Government", "Total")
ylabel <- paste0("Billion $ (",focal_year,")")
d <- sapply(models, calculateDemandByType, price_year=focal_year)
rownames(d) <- demand_types
p <- lineChartFigure(d / 10^9,ylabel)
p <- p + theme(text = element_text(size=12))
p
fig_num <- run_autonum(seq_id = "fig", pre_label = "Figure ", bkm = "demand-2")
block_caption("Demand by source",
              style = "Image Caption",
              autonum = fig_num
              )


```

Time series results are shown in Figure \@ref(fig:tsghg-1) and also Figure \@ref(fig:tsghg-2).

```{r ghg_time_series, echo=FALSE, fig.width=6.5, fig.height=8.5}
cbe_agg <- (aggregateStateResultMatrix(models[[1]], cbe_all, region=state) +
              aggregateStateResultMatrix(models[[1]], cbe_all, region='RoUS') +
              aggregateStateResultMatrix(models[[1]], cbe_all, region='RoW'))
households <- sweep(households_all, 2, cbe_agg['F010', ], "*") # convert from pct to mass
cbe_agg <- rbind(cbe_agg[rownames(cbe_agg) != 'F010', ], households)

p1 <- twoRegionTimeSeriesPlot(cbe_agg / 10^9, model = models[[1]], plottype = "bar")
p1 <- p1 + labs(y = "MMT CO2e")
p1
fig_num <- run_autonum(seq_id = "fig", pre_label = "Figure. ", bkm = "tsghg-1")
block_caption("CBE by sector (bar)",
              style = "Image Caption",
              autonum = fig_num
              )

p2 <- twoRegionTimeSeriesPlot(cbe_agg/ 10^9, model = models[[1]], plottype = "line")
p2 <- p2 + labs(y = "MMT CO2e")
p2
fig_num <- run_autonum(seq_id = "fig", pre_label = "Figure ", bkm = "tsghg-2")
block_caption("CBE by sector (line)",
              style = "Image Caption",
              autonum = fig_num
              )

```

Here is my figure reference Figure \@ref(fig:cbe_territorial).

```{r cbe_territorial, echo=FALSE, fig.width=6.5, fig.height=4}
ghgi_all <- sapply(models, getStateGHGI, simplify=TRUE, USE.NAMES=TRUE)

# Compare CBE to Territorial for Focal state
terr <- t(as.matrix(colSums(ghgi_all, na.rm = TRUE)))
cbe <- t(as.matrix(colSums(cbe_agg, na.rm = TRUE)))
combined <- as.matrix(rbind(terr, cbe))
rownames(combined) <- c("Territorial", "CBE")
p <- lineChartFigure(combined / 10^9, ylabel="MMT CO2e")
p <- p +
     scale_y_continuous(limits = c(0, NA)) +
     theme(text = element_text(size=12))
p
fig_num <- run_autonum(seq_id = "fig", pre_label = "Figure ", bkm = "cbe_territorial")
block_caption("Comparison to territorial",
              style = "Image Caption",
              autonum = fig_num
              )

```

Additional CBE figures by year are shown below.

```{r cbe_by_year, echo=FALSE, results='asis', fig.height=4, fig.width=6.5, warning=FALSE}
for(i in 1:length(cbe_by_year_list)) {
  print(cbe_by_year_list[[toString(years[i])]])
  fig_num <- run_autonum(seq_id = "fig", pre_label = "Figure ", bkm = paste0("CBE-", i))
  block_caption("CBE Results",
                style = "Image Caption",
                autonum = fig_num
                )
  ## Can't get captions to work inside the loop
}
```
