---
title: Select, Download, and Save a State EEIO Model locally"
output:
  md_document:
    variant: gfm
params:
  model:
    label: "Model Type"
    value: "v1.0"
    input: select
    choices: ["v1.0", "v1.1-GHG", "v1.1-GHGc"]
  years:
    label: "Model Year(s)"
    value: 2012
    input: select
    multiple: TRUE
    choices: [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
  states:
    label: "State(s)"
    value: ""
    input: select
    multiple: TRUE
    choices: ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL",
              "IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT",
              "NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI",
              "SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"]
  write:
    label: "Write to Excel?"
    value: FALSE
---

```{r setup, include=FALSE}
source("../R/utils.R")

## Select model build parameters
states <- params$states
years <- params$years
spec <- params$model

if (spec == "v1.0") {
  modelstub <- 'EEIOv1.0-s-'
} else if (spec == "v1.1-GHG") {
  modelstub <- 'EEIOv1.1-GHG-'
} else if (spec == "v1.1-GHGc") {
  modelstub <- 'EEIOv1.1-GHGc-'
}

```

```{r load-model, echo=FALSE}
if (params$write) {
  install_useeior()
  # prepare output directory
  output_dir <- file.path('../output')
  dir.create(output_dir, showWarnings = FALSE)
}

for(state in states) {
  if((modelstub == 'EEIOv1.1-GHGc-') & (!state %in% c("VT", "NY", "ME"))) {
    stop(paste0(state, " not available with a customized GHG Inventory, please use v1.1-GHG."))
  } else if ((modelstub == 'EEIOv1.1-GHG-') & (state %in% c("VT", "NY", "ME"))) {
    stop(paste0(state, " is only available with a customized GHG Inventory, please use v1.1-GHGc."))
  }
  for(year in years) {
    modelname <- paste0(state, modelstub,substr(year,3,4)) 
    file_path <- download_model_RDS(modelname)

    model <- readRDS(file_path) # Test that it loads correctly
    if(params$write) {
      useeior::writeModeltoXLSX(model, output_dir)
      print(paste0("Model for ", state, " in ", year, " written to Excel at ", output_dir, "."))
    }
  }
}

```
